version: '3.8'
services:
  db:
    container_name: raygallery_db
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ram@#123$
      POSTGRES_DB: raygallery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
